(#2456) .net 6.0 support
Update TestProjectGenerator
update build.yml
 fix test discovery and timeout problem for TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests
Add Microsoft.TestPlatform.TestHost package.
Adjust git.log Use .net 6.0.100-rc.2.21505.57 as net6SdkVersion
Use vmImage: 'ubuntu-20.04' because of ##[warning]
An image label with the label Ubuntu16 does not exist.
Fix build.ps1 to show --no-restore option Ignore "Scenario: Two projects with the same unit test provider using MSBuild" because msbuild for 2019 is not able to handle it
Add net6 to template.json
Fix CreateEmtpyCSharpNet60ProjectInNewFormat test Tag "Scenario: Use MSBuild for compiling" with @IgnoreOnWmImage2019
Do not try to delete packages folder on Azure's "Windows_NT" because it is restricted
@globalusingdirective #MSBuild for VS2019 throws error CS8652: The feature 'global using directive' is currently in Preview and unsupported. Remove @WindowsOnly